[project]
name = "team3-hackathon2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ioannis Bogris", email = "bogrisgiannis@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=1.6.4",
    "langchain-openai>=1.6.5",
    "langchain-postgres>=0.0.18",
    "langchain-text-splitters>=1.1.2",
    "psycopg[binary]>=3.3.6",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
team3-hackathon2 = "team3_hackathon2:main"

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"
