[project]
name = "team3-hackathon2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ioannis Bogris", email = "bogrisgiannis@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.7.18",
    "dotenv>=0.9.9",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-openai>=1.6.5",
    "langchain-postgres>=0.0.18",
    "langchain-text-splitters>=1.1.2",
    "langfuse>=4.15.4",
    "langgraph-checkpoint-postgres>=3.1.2",
    "mcp>=1.30.0",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
]

[project.scripts]
team3-hackathon2 = "team3_hackathon2:main"

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"
